### ISSUE TITLE
add an emoji folder to language

### ISSUE THREAD

**Issue by suisea** [dariusk/corpora#127]
pls and ty

**Comment by dariusk** [comment]
Thanks for the reminder, fixed in 524c8d069144021c07a4ff5ef715b80ce167e18b

**Comment by suisea** [comment]
ty~

**Comment by kswedberg** [comment]
@dariusk: Unless someone else gets to it first, I'm gonna put together a json file of all the Unicode emoji from http://unicode.org/emoji/charts/full-emoji-list.html tonight. Was thinking of this format:

```
{
  "description": "A list of Unicode emoji",
  "source": "http://unicode.org/emoji/charts/full-emoji-list.html",
  "emoji": [
    {
      "code": "U+1F600",
      "character": "😀",
      "name": "grinning face",
      "version": 6.1,
      "tags": [
        "grin",
        "face",
        "person"
      ]
    },
    //...
  ]
}
```

Thoughts?

**Comment by dariusk** [comment]
@kswedberg Sounds good! It's only ~1200 entries so that works.

**Comment by suisea** [comment]
that seems like a pretty big list/corpus for corpora but in the end it's
not my call

**Comment by kswedberg** [comment]
Would it be better to break them up into a separate file for each category (e.g. smileys-people.json, animals-nature.json, food-drink.json)?

**Comment by suisea** [comment]
i had darius add this category to provide curated lists of emoji that
differed from the original categorisations, which are so broad as to not be
useful. you can go ahead but i think i wanted to add to corpora only
something specific that wouldn't be so easily found elsewhere? idk

**Comment by dariusk** [comment]
Per the readme, complete, non-curated lists of things (like major U.S. cities) are allowed as long as they're about 1000 items long. I think emoji falls into that bucket. For example I might find it not very useful to have a list of emoji here, but for a student who is attending a workshop it could be very useful to have it all in machine-readable format.

**Comment by suisea** [comment]
makes sense!

**Comment by kswedberg** [comment]
It was the machine-readable aspect that I thought would make it useful. Ok, I'll go ahead with it then.

**Comment by kswedberg** [comment]
@dariusk : I scraped the unicode table and created the json as described above. Now that I've done it, though, I'm thinking it's probably more data than you'd want. With the json pretty-printed, it comes out to ~16,500 lines. It's so big that my [Atom text editor](https://atom.io/) chokes on it.

If you still want it, let me know and I'll send a pull request. Otherwise, I'll send it to the trash bin.

Thanks!

**Comment by suisea** [comment]
@kswedberg is atom good with emoji? neither vim nor sublime is (i've heard emacs, tho...)

**Comment by kswedberg** [comment]
@suisea It's fine with the emoji (I'm running OS X, if that matters). It's just the file size that bogs it down. Lots of stuff to syntax-highlight.

**Comment by coleww** [comment]
i have a few emoji lists over in weird-corpora-land https://github.com/coleww/weirdly-specific-corpora/tree/master/data/emoji that i can move over. they probably need to be curated a lil better tho

**Comment by suisea** [comment]
@coleww gdi cole u stole my thunder smh :zap:
