### ISSUE TITLE
A list of profane english words ?

### ISSUE THREAD

**Issue by neo01124** [dariusk/corpora#147]
(Not sure if an issue should be opened)

Is there such a list in the corpora ? Couldn't find it with a quick search ? Would it be interesting to have ?

**Comment by hugovk** [comment]
Not in Corpora, but try https://github.com/dariusk/wordfilter or [any of these](https://github.com/dariusk/NaNoGenMo-2015/issues/1#issuecomment-160394731).

**Comment by neo01124** [comment]
thanks a lot. 
Some of them are quite specific but still a good starting point.
