### ISSUE TITLE
Fix attributions?

### ISSUE THREAD

**Issue by sethwoodworth** [dariusk/corpora#158]
A TON of folks have contributed files to corpora, but only three people are cited in the contributor's section of the README.  Would you accept a PR to add the other contributors to the readme as a separate file?

**Comment by dariusk** [comment]
Yes although I would want to get consent from people to be included. I
presumed that people who didn't add themselves didn't want to be listed
there. (Explicit credit being different from an entry in the commit log)

**Comment by Lumiras** [comment]
Could we just put our consent in this issue if we're OK with it? If so, I'm alright with being added so it can all be done in one PR

**Comment by coleww** [comment]
https://help.github.com/articles/setting-guidelines-for-repository-contributors/ not the best solution, but a CONTRIBUTING.md would at least get linked to when people open a PR, and the info on adding yourself as a listed contributor could be there.

**Comment by enkiv2** [comment]
I'm fine with being added.

**Comment by dariusk** [comment]
Let's collect prior contributions in this issue and also add a pull request
with a CONTRIBUTING.md informing future contributors that they should add
themselves and/or make a note in their own PR. I'm traveling and can't do
that but if someone else wants to take a shot at it please do.

**Comment by hugovk** [comment]
Fine with being added.

---

There already exists this auto-generated page showing all the contributors that GitHub knows about:
https://github.com/dariusk/corpora/graphs/contributors

I've seen [other projects](https://github.com/python-pillow/Pillow#python-imaging-library-fork) just use that like this:

> ... by [Darius Kazemi and Contributors](https://github.com/dariusk/corpora/graphs/contributors).

**Comment by Hectate** [comment]
I'm good with being added.
I'll note that I presumed that Github already tracks contributors so it would be public knowledge anyway.

**Comment by dariusk** [comment]
Okay, I implemented the "Darius Kazemi and Contributors" suggestion in 3367bc8
