### ISSUE TITLE
dulux colours

### ISSUE THREAD

**Issue by josephrocca** [dariusk/corpora#246]
Hopefully someone can format and make a pull request :)
[dulux colours.txt](https://github.com/dariusk/corpora/files/744159/dulux.colours.txt)
source: http://www.dulux.com.au/specifier/colour/colour-atlas

**Comment by hugovk** [comment]
Remember contributions must be CC0/public domain. Can Dulux colour names be submitted under that?

https://github.com/dariusk/corpora#license
https://github.com/dariusk/corpora#i-have-some-data-how-do-i-submit

**Comment by dariusk** [comment]
Good point here. Also worth discussing potential removal of [Crayola colors](https://github.com/dariusk/corpora/commit/1be5fa4cccf13704afd405ccc95f914751957f8b).

**Comment by blinkdog** [comment]
In general, names are not eligible for Copyright protections:
[What Does Copyright Protect?](https://www.copyright.gov/help/faq/faq-protect.html)
[Copyright Protection Not Available for Names, Titles, or Short Phrases](https://www.copyright.gov/circs/circ34.pdf)

It's possible to obtain Trademark protection for some names, but my guess is the companies publishing these colors would like to see widespread usage. That is, they'd rather you refer to the color by the name they picked, not the name that a competitor picked.

**Comment by enkiv2** [comment]
It's very common for color names to be trademarked or for color <-> name
associations to be copyrighted (as with Pantone). However, I haven't been
able to find any information about licensing from Dulux in a quick search,
which probably indicates that they haven't attempted a trademark (and a
copyright for associations wouldn't apply to a list of color names if we
don't attach the associated RGB value).

If we want to check, the easiest way would be to see what trade names Dulux
has registered.

**Comment by enkiv2** [comment]
According to TESS, the USPTO's search engine for trademarks, there's only
one trade name associated with any company with "dulux" in the name -- that
being an unrelated company's unrelated product. So, it looks safe to me.

**Comment by dariusk** [comment]
Done!
