### ISSUE TITLE
Ultraconserved words

### ISSUE THREAD

**Issue by mathpunk** [dariusk/corpora#268]
I read this and immediately thought of this repo.

[Lingists identify 15,000-year-old 'ultraconserved words'](https://www.washingtonpost.com/amphtml/national/health-science/linguists-identify-15000-year-old-ultraconserved-words/2013/05/06/a02e3a14-b427-11e2-9a98-4be1688d7d84_story.html)

I don't know how I'd begin finding and processing them.

**Comment by dariusk** [comment]
Found it on archive.org if you want to give it a go! https://web.archive.org/web/20130730055805/https://webspace.utexas.edu/bighamds/LIN312/Files/Swadesh.pdf

**Comment by mathpunk** [comment]
This keeps failing to get onto my actually-going-to-do list.

**Comment by hugovk** [comment]
https://twitter.com/dorrismccomics/status/877171503456014341 :)
