### ISSUE TITLE
Paint Colors

### ISSUE THREAD

**Issue by luismqueral** [dariusk/corpora#81]
Currently working on a project that requires a bunch of different, often ridiculous, names of various paints (from Valspar, Benjamin Moore, etc.). Currently scraping color pickers and random sites for paint names. 

Slowly...but surely...

Would anyone be interested in a big list of them? Not really familiar with packing things up in JSON but I can do my best :-).

**Comment by metavida** [comment]
I'm sure that list would fit in quite nicely I this site!

Creating a JSON file is quite straightforward, but to make your job simpler, here's a tinplate that you can use, simply adding more paint names to the quoted comma-separated list of "paint_brands"

```json
{
  "description": "A list of brands that make residential paints.",
  "paint_brands": [
    "Benjamin Moore", "Velspar"
  ]
}
```

Once you've completed your list list in JSON you can paste it here to make sure it's valid JSON: http://jsonlint.com/

**Comment by luismqueral** [comment]
Here's what I currently have: https://docs.google.com/spreadsheets/d/1_Sjj747b2P66p6H2U--sEG34ymXjsKlC-2ujZYs3Qmk/edit?usp=sharing

Is there a way to automate this? Say I can pick a "paint brand" and then automatically add the corresponding colors? There are thousands of these guys.

**Comment by metavida** [comment]
Woah, that's a lot of colors! (And more coming, I'm sure :smile: )

Disclaimer: I don't speak for this project. I'm just a person from the Internet that finds this project interesting. 

In [Corpora's README](https://github.com/dariusk/corpora/blob/master/README.md) there are the following lines:

> Corpora is a collection of small files. It is not meant to be an exhaustive source of anything: a list of resources should contain somewhere in the vicinity of 1000 items.
> For example, Corpora will not contain any complete "dictionary" style files. Instead we host a sampling of 1000 common nouns, adjectives, and verbs.

This makes me think that the comprehensive list you're gathering may not actually be a great fit as is. **However** a selection of 1,000 paint colors from various brands seems like it might fit in well with [the existing lists of colors.](https://github.com/dariusk/corpora/tree/master/data/colors)

How does that sound to you? If it seems reasonable I'd be willing to put in an hour or so of work to write a script that'd generate a JSON file with a random selection of unique colors. Either that or you could hand-pick your favorite 1,000 colors & put them in a new tab or file for me to convert to JSON.

**Comment by metavida** [comment]
@luismqueral I created a JSON file for inclusion in this project (see #85). It includes 1,000 paint colors picked at random from the 3 brands that you have data on in your Google Doc. If you do end up collecting paint colors from more brands and add them to that Google Doc, it'd be quite trivial for me to regenerate the JSON file, including some of those new paint colors.

**Comment by luismqueral** [comment]
metavida, didn't get a chance to thank you for that JSON file!
